name: 'TODO'
branding:
  icon: 'package'
  color: 'orange'
description: |
  In case lock file is updated, action will output versions differences as summary
inputs:
  lock-file:
    required: true
    description: 'path to the lock file from the repository root'
    default: 'composer.lock'
  req-file:
    required: true
    description: 'path to the requirement file from the repository root'
    default: 'composer.json'

runs:
  using: "composite"
  steps:
    # Even if an input is marked as "required", an empty value (or no value) may be passed !
    - name: Validate inputs
      uses: actions/github-script@v7
      env:
        INPUT_LOCK_FILE: ${{ inputs.lock-file }}
        INPUT_REQ_FILE: ${{ inputs.req-file }}
      with:
        script: |
          core.info('Validate inputs');
          
          core.getInput('lock-file', {required: true});
          core.getInput('req-file', {required: true});

    #### TODO
    #### - Manage push vs pr (for head and base sha)
    #### - Manage OS + Proc (for the binary to run)
    #### - Consider using github-script to download the files (easier/faster than a checkout, which is actually fetch under the user workspace)

    - name: Fetch previous files
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: current
        sparse-checkout: |
          ${{ inputs.req-file }}
          ${{ inputs.lock-file }}

    - name: Fetch current files
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.base.sha }}
        path: previous
        sparse-checkout: |
          ${{ inputs.req-file }}
          ${{ inputs.lock-file }}
        sparse-checkout-cone-mode: false

    - name: Perform diff
      run: |
        ${{ github.action_path }}/bin/gha-composer-diff-linux-amd64 \
          -previous-req previous/${{ inputs.req-file }} \
          -previous-lock previous/${{ inputs.lock-file }} \
          -current-req current/${{ inputs.req-file }} \
          -current-lock current/${{ inputs.lock-file }} \
        > summary.md
      shell: bash

    - name: Build summary
      run: |
        echo "# 🔎 Composer packages 🔍 " >> $GITHUB_STEP_SUMMARY
        cat summary.md >> $GITHUB_STEP_SUMMARY
      shell: bash
