name: 'TODO'
branding:
  icon: 'package'
  color: 'orange'
description: |
  In case lock file is updated, action will output versions differences as step summary

inputs:
  lock-path:
    required: true
    description: 'Path to the lock file from the repository root'
    default: 'composer.lock'
  req-path:
    required: true
    description: 'Path to the requirement file from the repository root'
    default: 'composer.json'
  with-step-summary:
    required: true
    description: 'Whether to output the summary in the step summary'
    default: 'true'

outputs:
  summary:
    value: ${{ steps.summary-builder.outputs.step_summary }}
    description: 'Summary of the differences between the previous and current files'

runs:
  using: "composite"
  steps:
    # Even if an input is marked as "required", an empty value (or no value) may be passed !
    - uses: actions/github-script@v9
      with:
        script: |
          core.debug('Fetch deps');
          function getInput(name) { return core.getInput(name, {required: true}) }
          
          core.info('Validate inputs');
          
          getInput('req-path');
          getInput('lock-path');

    - uses: actions/github-script@v9
      id: info
      env:
        INPUT_ACTION-PATH: ${{ github.action_path }}
        INPUT_TMP-PATH: ${{ runner.temp }}
      with:
        script: |
          core.debug('Fetch deps');
          const os = require('os');
          const path = require('path');
          function getInput(name) { return core.getInput(name, {required: true}) }
          
          core.info('Determine binary to run');
          let platform = os.platform();
          switch (platform) {
            case 'win32':
              platform = 'windows';
              break;
            case 'darwin':
            case 'linux':
              break;
            default:
              core.setFailed(`Unsupported architecture: ${arch}`);
          }
          let arch = os.arch();
          switch (arch) {
            case 'x64':
              arch = 'amd64';
              break;
            case 'arm64':
              break;
            default:
               core.setFailed(`Unsupported architecture: ${arch}`);
          }
          
          core.setOutput(
            'binary', 
            getInput('action-path') + core.toPlatformPath('/bin/' + platform + '-' + arch + '-wrapper')
          );
          
          core.info('Set previous and current refs as inputs');
          core.setEnv('INPUT_PREVIOUS-REF', context.payload.pull_request.base.sha ?? context.payload.before);
          core.setEnv('INPUT_CURRENT-REF', context.payload.pull_request.head.sha ?? context.payload.after);
          
          core.info('Set intermediate inputs and env variables');
          const tmpPath = getInput('tmp-path');
          core.setEnv('INPUT_TMP-PATH', tmpPath); // To be automatically available for the next steps as input
          // For bash scripts
          core.setEnv('DIFF_SUMMARY_PATH', path.join(tmpPath, 'diff_summary.md'))
          core.setEnv('STEP_SUMMARY_PATH', path.join(tmpPath, 'step_summary.md'))
          
          

    - uses: actions/github-script@v9
      id: fetch-files
      with:
        script: |
          core.debug('Fetch deps');
          const fs = require('fs').promises;
          const path = require('path');
          const getContent = github.rest.repos.getContent;
          const [repoOwner, repoName] = [context.payload.repository.owner.login, context.payload.repository.name];
          function getInput(name) { return core.getInput(name, {required: true}) }
          async function getFileContent(path, ref) {
            core.debug(`Fetch file content for path="${path}" and ref="${ref}"`);
            const {data} = await getContent({owner: repoOwner, repo: repoName, path, ref});
            if (data.type !== 'file') {
              throw new Error(`Expected type="file" but received "${data.type}" !`);
            } else if (data.encoding !== 'base64') {
              throw new Error(`Expected base64 encoded file but received "${data.encoding}" !`);
            }
            
            return Buffer.from(data.content, 'base64').toString('utf-8');
          }
          
          core.info('Fetch previous and current file contents');
          const [reqRepoPath, lockRepoPath] = [getInput("req-path"), getInput("lock-path")];
          const [reqFilename, lockFilename] = [path.basename(reqRepoPath), path.basename(lockRepoPath)];
          const [prevRef, currRef] = [getInput("previous-ref"), getInput("current-ref")];
          
          const [previousReqContent, previousLockContent, currentReqContent, currentLockContent] = await Promise.all([
            getFileContent(reqRepoPath, prevRef),
            getFileContent(lockRepoPath, prevRef),
            getFileContent(reqRepoPath, currRef),
            getFileContent(lockRepoPath, currRef)
          ]);
          
          core.info('Write files to disk');
          const basePath = getInput('tmp-path');
          const [previousReqOutPath, previousLockOutPath, currentReqOutPath, currentLockOutPath] = [
            path.join(basePath, "previous-" + reqFilename),
            path.join(basePath, "previous-" + lockFilename),
            path.join(basePath, "current-" + reqFilename),
            path.join(basePath, "current-" + lockFilename)
          ]
          
          await Promise.all([
            fs.writeFile(previousReqOutPath, previousReqContent),
            fs.writeFile(previousLockOutPath, previousLockContent),
            fs.writeFile(currentReqOutPath, currentReqContent),
            fs.writeFile(currentLockOutPath, currentLockContent)
          ])
          
          core.debug('Configure env variables');
          // For bash scripts
          core.setEnv('PREVIOUS_REQ_PATH', previousReqOutPath);
          core.setEnv('PREVIOUS_LOCK_PATH', previousLockOutPath);
          core.setEnv('CURRENT_REQ_PATH', currentReqOutPath);
          core.setEnv('CURRENT_LOCK_PATH', currentLockOutPath);

    - shell: bash
      run: |
        # Perform diff
        
        ${{ steps.info.outputs.binary }} ${{ runner.debug && '-d' || '' }} \
          -previous-req  ${PREVIOUS_REQ_PATH} \
          -previous-lock ${PREVIOUS_LOCK_PATH} \
          -current-req   ${CURRENT_REQ_PATH} \
          -current-lock  ${CURRENT_LOCK_PATH} \
        > ${DIFF_SUMMARY_PATH}

    - shell: bash
      id: summary-builder
      run: |
        # Build summary
        
        echo "# 🔎 Composer packages 🔍 " > ${STEP_SUMMARY_PATH}
        cat ${DIFF_SUMMARY_PATH} >> ${STEP_SUMMARY_PATH}
        
        echo "step_summary<<__SUMMARY_EOF__" >> $GITHUB_OUTPUT
        cat ${STEP_SUMMARY_PATH} >> $GITHUB_OUTPUT
        echo "__SUMMARY_EOF__" >> $GITHUB_OUTPUT

    - shell: bash
      if: inputs.with-step-summary == 'true'
      run: |
        # Post summary
        
        cat ${STEP_SUMMARY_PATH} >> $GITHUB_STEP_SUMMARY
